# Generated by Django 4.2.6 on 2023-10-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.session')),
            ],
            options={
                'db_table': 'customsessions',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('session_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='database.customsession')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
