# Generated by Django 4.2.6 on 2023-10-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='session_id',
        ),
        migrations.AddField(
            model_name='customsession',
            name='cities',
            field=models.ManyToManyField(to='database.city'),
        ),
    ]
