# Generated by Django 4.2.6 on 2023-10-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_city_session_id_customsession_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
