# Generated by Django 4.2.6 on 2023-10-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_city_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customsession',
            table='customsessions',
        ),
    ]
