# Generated by Django 4.2.6 on 2023-10-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('database', '0003_alter_customsession_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsession',
            name='id',
        ),
        migrations.AlterField(
            model_name='customsession',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sessions.session'),
        ),
    ]
