# Generated by Django 4.2.6 on 2023-10-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_customsession_id_alter_customsession_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsession',
            old_name='session',
            new_name='session_ptr',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
