# Generated by Django 4.2.6 on 2023-10-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rename_session_customsession_session_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsession',
            name='city',
        ),
        migrations.AddField(
            model_name='customsession',
            name='city',
            field=models.ManyToManyField(to='database.city'),
        ),
    ]
