# Generated by Django 4.2.6 on 2023-10-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_customsession_city_customsession_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customsession',
            old_name='city',
            new_name='cities',
        ),
    ]
