version: '3.9'


services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./src/frontend/humalect-weather-app
      dockerfile: Dockerfile

    env_file:
      - ./.env
    ports:
      - '3000:3000'

    volumes:
      - ./volumes/frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./src/backend/humalect_weather_app
      dockerfile: Dockerfile

    env_file:
      - ./.env
    ports:
      - '8000:8000'

    volumes:
      - ./volumes/backend:/app/backend

    depends_on:
      - db