version: '3.9'


services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./src/frontend/humalect-weather-app
      dockerfile: Dockerfile

    environment:
      - VITE_REACT_APP_BACKEND_API_ENDPOINT=http://localhost:8000/humalect-weather-api/v1
    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./src/backend/humalect_weather_app
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - ACCUWEATHER_API_KEY=rltT7F44G5YRR8y1CGOWWEHYEdf7VLkL
      - ACCUWEATHER_BASE_URL=http://dataservice.accuweather.com

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db